Repository ReVanced/revanced-api, pull requests merged in 2023-10, with the labels that each got.

#104 feat: added branding
  api/models/info.py
  config.py
Labels: modification

#102 feat: `/announcements` endpoint and other additions
  .dockerignore
  .github/workflows/codeql.yml
  .github/workflows/dev.yml
  .github/workflows/main.yml
  .github/workflows/pytest.yml
  .github/workflows/quodana.yml
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  README.md
  api/__init__.py
  api/announcements.py
  api/login.py
  api/models/announcements.py
  api/models/info.py
  api/models/socials.py
  app.py
  auth.py
  config.py
  data/database.py
  data/models.py
  docker-compose.yml
  docker/run-backend.sh
  docker/run-healthcheck.sh
  limiter.py
  persistance/.gitkeep
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: modification, ci, hacktoberfest-accepted

#108 fix(ci): revert "build: slim down the docker container (#60)"
  .dockerignore
  .gitignore
  Dockerfile
  docker/run-backend.sh
  docker/run-healthcheck.sh
  poetry.lock
  requirements.txt
Labels: bug, hacktoberfest-accepted

#109 fix(ci): install python deps
  Dockerfile
Labels: ci, hacktoberfest-accepted

#110 fix(ci): add git dep
  Dockerfile
Labels: ci, hacktoberfest-accepted

#111 feat: Disallow all web crawlers
  api/__init__.py
  api/robots.py
Labels: feature-request, hacktoberfest-accepted
